# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Peiqi Blog
subtitle: 青囊卖卜
description: 若无闲事挂心头, 便是人间好时节
keywords: 佩奇的博客, 青囊卖卜,Peiqi Blog
author: jupeiqi
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://jupeiqi.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts 与Jekyll兼容，可以直接将Jeykyll博客复制进_post文件夹下
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true # 在控制台用 hexo new post title 创建博客时，会在_post文件夹中生成一个与博客对应的专门存放数据的文件夹，方便管理

relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs: # 代码高亮
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 12
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: 
   github: https://github.com/jupeiqi/jupeiqi.github.io.git
  #  gitee: https://gitee.com/jupeiqi/jupeiqi.gitee.io.git
  #  coding: https://e.coding.net/jupeiqi/jupeiqi/jupeiqi.git
  branch: master


search:
  path: search.xml
  field: post

permalink_pinyin: # 使在生成文章时生成中文拼音的永久链接
  enable: true
  separator: '-' # default: '-'

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

githubEmojis: # 对应的markdown emoji语法（::,例如：:smile:）转变成会跳跃的emoji表情
  enable: true
  className: github-emoji
  inject: true
  styles:
  customEmojis:


# hexo-douban
douban:
  id: 162448367 # 自己的豆瓣id号
  book:
    path: books/index.html
    title: '那些年，我翻阅过的书'
    quote: '思想和身体，总有一个在路上'
  movie:
    path: movies/index.html
    title: '那些年，我追过的电影'
    quote: '过去、现在、和未来'
  game:
    path: games/index.html
    title: '那些年，我玩过的游戏'
    quote: '还记得你曾经的游戏角色吗'
  timeout: 10000 

# offline config passed to sw-precache.
service_worker:
  maximumFileSizeToCacheInBytes: 5242880
  staticFileGlobs:
  - public/**/*.{js,html,css,png,jpg,gif,svg,eot,ttf,woff,woff2}
  stripPrefix: public
  verbose: false
